# Generated by Django 4.0 on 2021-12-07 22:42

from django.db import migrations
from ..models import Instructor, Student, Course, StudentCourse

def seed_data(apps, schema_editor):
    s1 = Student(first_name='Jake', last_name='Sisko', year=9, gpa=4.0)
    s2 = Student(first_name='Keira', last_name='Nerys', year=10, gpa=3.5)
    s3 = Student(first_name='Julian', last_name='Bashir', year=11, gpa=4.4)
    s4 = Student(first_name='Molly', last_name='OBrien', year=12, gpa=3.0)
    s5 = Student(first_name='Keiko', last_name='Ishikawa', year=9, gpa=4.2)
    s6 = Student(first_name='Eli', last_name='Garak', year=10, gpa=3.0)
    s7 = Student(first_name='Thomas', last_name='Riker', year=11, gpa=2.5)
    s8 = Student(first_name='Michael', last_name='Eddington', year=12, gpa=3.7)
    s9 = Student(first_name='Beckett', last_name='Mariner', year=9, gpa=3.8)
    s10 = Student(first_name='Sam', last_name='Rutherford', year=9, gpa=2.0)

    i1 = Instructor(first_name='Jackie', last_name='Daytona', hire_date='2001-10-10')
    i2 = Instructor(first_name='Colin', last_name='Robinson', hire_date='2009-04-10')
    i3 = Instructor(first_name='Guillermo', last_name='de la Cruz', hire_date='2009-11-18')
    i4 = Instructor(first_name='Poppy', last_name='Li', hire_date='2011-07-08')
    i5 = Instructor(first_name='Ian', last_name='Grimm', hire_date='2018-11-05')
    i6 = Instructor(first_name='Brad', last_name='Baskshi', hire_date='2020-02-02')

    c1 = Course(name='Math', instructor=i4, credits=5)
    c2 = Course(name='Science', instructor=i2, credits=5)
    c3 = Course(name='Humanities', instructor=i1, credits=4)
    c4 = Course(name='Programming', instructor=i4, credits=10)
    c5 = Course(name='Creative Writing', instructor=i5, credits=4)
    c6 = Course(name='Economics', instructor=i6, credits=5)
    c7 = Course(name='Self Defense', instructor=i3, credits=3)
    c8 = Course(name='Volleyball', instructor=i1, credits=3)
    c9 = Course(name='History', instructor=i2, credits=4)
    c10 = Course(name='Art', instructor=i5, credits=5)

    sc1 = StudentCourse(student=s1, course=c5, grade='A+')
    sc2 = StudentCourse(student=s1, course=c1, grade='A')
    sc3 = StudentCourse(student=s1, course=c2, grade='A')
    sc4 = StudentCourse(student=s10, course=c9, grade='B+')
    sc5 = StudentCourse(student=s2, course=c10, grade='A')
    sc6 = StudentCourse(student=s2, course=c8, grade='B-')
    sc7 = StudentCourse(student=s2, course=c2, grade='A+')
    sc8 = StudentCourse(student=s10, course=c4, grade='A')
    sc9 = StudentCourse(student=s3, course=c3, grade='C+')
    sc10 = StudentCourse(student=s3, course=c1, grade='B')
    sc11 = StudentCourse(student=s3, course=c2, grade='B-')
    sc12 = StudentCourse(student=s10, course=c7, grade='B+')
    sc13 = StudentCourse(student=s4, course=c10, grade='A+')
    sc14 = StudentCourse(student=s4, course=c7, grade='A-')
    sc15 = StudentCourse(student=s4, course=c5, grade='A+')
    sc16 = StudentCourse(student=s5, course=c4, grade='B+')
    sc17 = StudentCourse(student=s5, course=c5, grade='A+')
    sc18 = StudentCourse(student=s5, course=c1, grade='A')
    sc19 = StudentCourse(student=s5, course=c2, grade='C')
    sc20 = StudentCourse(student=s6, course=c6, grade='B+')
    sc21 = StudentCourse(student=s6, course=c10, grade='A')
    sc22 = StudentCourse(student=s6, course=c8, grade='B-')
    sc23 = StudentCourse(student=s7, course=c9, grade='A+')
    sc24 = StudentCourse(student=s7, course=c4, grade='A')
    sc25 = StudentCourse(student=s7, course=c3, grade='C+')
    sc26 = StudentCourse(student=s7, course=c6, grade='B')
    sc27 = StudentCourse(student=s8, course=c2, grade='B-')
    sc28 = StudentCourse(student=s8, course=c9, grade='B+')
    sc29 = StudentCourse(student=s9, course=c8, grade='C+')
    sc30 = StudentCourse(student=s9, course=c7, grade='A-')
    sc31 = StudentCourse(student=s9, course=c5, grade='A+')
    sc32 = StudentCourse(student=s9, course=c4, grade='B+')
    sc33 = StudentCourse(student=s2, course=c4, grade='A')

    
    data = [s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, i1, i2, i3, i4, i5, i6, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, sc1, sc2, sc3, sc4, sc5, sc6, sc7, sc8, sc9, sc10, sc11, sc12, sc13, sc14, sc15, sc16, sc17, sc18, sc19, sc20, sc21, sc22, sc23, sc24, sc25, sc26, sc27, sc28, sc29, sc30, sc31, sc32, sc33 ]

    for item in data:
        item.save()



class Migration(migrations.Migration):

    dependencies = [
        ('school_db', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
